### PR TITLE
AniSkip Implementation 

### PR DESCRIPTION
**Pull request by ch0nker**
Implements AniSkip's API for a more accurate skip button, it also keeps the original in case of AniSkip doesn't have it.
- Idea came from https://github.com/akuse-app/akuse/discussions/109#discussioncomment-10068808.

## Changes
- Intro, Outro, and Recap skip buttons (if AniSkip has them).

## Screenshots
Screenshot_20240901_161816
Screenshot_20240901_161843

### CODE REVIEW

**Comment by aleganza** [comment]
you are cooking

**Comment by ch0nker** [comment]
> you are cooking

Lmao thanks.

Should be ready to merge, if you're planning on adding this.

**Comment by aleganza** [comment]
are you inside the discord server? if so what's ur username?

**Comment by ch0nker** [comment]
> are you inside the discord server? if so what's ur username?

I just joined it my username is chonkiest_chonk my GitHub is linked to it as well

**Pull request merged**
