### PR TITLE
Discord RPC Details

### PR DESCRIPTION
**Pull request by synthofficial**
Discord RPC will now show as below (reverts back to normal when closing the player)

image

### CODE REVIEW

**Comment by aleganza** [comment]
heyy you could have kept this pr open... I'm just waiting to merge it because I need to publish the macos version first

**Comment by synthofficial** [comment]
i merged this with goofy's pr :)

**Comment by aleganza** [comment]
I don't see it

**Comment by ghost** [comment]
I haven't put my pr up yet because I'm still adding things and working things out for right now.

**Comment by aleganza** [comment]
ahh perfect it was just to be sure!
btw does this pr add more than only discord rpc activity status?

**Comment by ghost** [comment]
yes, right now it has the RPC that was merged and the user page which has the users watch list etc right now im working on a airing schedule and i might not be done with it today

**Comment by aleganza** [comment]
It would be much better if you could make 2 different prs, in fact I didn't even know this one included user page too.

**Comment by ghost** [comment]
> ahh perfect it was just to be sure! btw does this pr add more than only discord rpc activity status?

were you meaning this pr? if so then no only rpc is in this one. sorry for the confusion if you were meaning this pr, i thought you meant the one i havnt put up yet lol.

**Comment by aleganza** [comment]
yep this one. If I look at the commits I see changes at tab 2, 3, 4 and navbar, but there also the changes for the discord rpc, so this pr includes both of them.
I know you still have to publish yours with the user tab changes, but this one doesn't have only discord rpc activity status feature.
don't know why discord rpc got merged with user page

**Comment by synthofficial** [comment]
if needed, i can make a pr with just the discord rpc? seems like it would make it easier

**Comment by aleganza** [comment]
absolutely

**Pull request closed without merging**
