### PR TITLE
Local History & Other QoL features

### PR DESCRIPTION
**Pull request by ch0nker**
This is literally my first time interacting with React and Typescript so there is probably some noob errors, so I apologize in advance about that.

##  Changes
(Checked => will be added)

- [x] - Local History: Keep track of where you left off locally instead of relying on Anilist.
- [x] - Customize Episodes Per Page: Adds a text input inside of the settings so you can change the amount.
- [x] - Removes Laptop Icon: I just made the login button open the modal instead.
- [x] - More space at the bottom of Tab1: The navbar hides information for the last section so I added some more space.
- [x] - Rewrote setDefaultStoreVariables: Made it so uses a table to set values instead of copy and pasting ```if (!STORE.has(KEY)) STORE.set(KEY, VALUE);```.
- [x] - Schedule Tab: A new tab for time based entries.
- [x] - Search Pages: Increment pages by scrolling to the bottom.

## Todos
- [ ] Progress bars in EpisodesSection

## Issues
- #64: Adds watch history.
- #75: Could probably filter the "Continue Watching" so new episodes are put first.
- #135: Updates the "Continue Watching" section whenever you close the anime modal and keeps track of watch history without needing to finish the episode.
- #72: Fixes issue "A" by adding pages by scrolling down.

## Screenshots
Screenshot_20240831_235920
Screenshot_20240829_224122
Screenshot_20240829_224702
Screenshot_20240829_224752

### CODE REVIEW

**Comment by aleganza** [comment]
Hi! thank you for you big pr, I'm gonna ask you some questions:
Local history: did you just add a local episode progress tracking or did you also changed something about the anilist client?
Watchlist: what is it?
Schedule Tab: does it fetch the data from anilist?

**Comment by ch0nker** [comment]
Local History: I just added local episode progress I didn't mess with how it updates on anilist.
Watchlist: Is essentially what the old "Continue Watching" section was but adds the "PLANNING" list, could probably remove it didn't realize there was a library tab before creating it.
Schedule Tab: Does fetch from anilist using the airingSchedules thing.

**Comment by aleganza** [comment]
Alright now I'm checking you pr. I made a checkbox list to check what I think should be added and what not

**Comment by aleganza** [comment]
Almost everything is perfect. I would ask you to:
- Remove Watchlist and keep the Continue Watching as it was, so I prefer it to be the Current data from anilist instead of the progress tracked anime. You can absolutely keep the progress tracking but I don't want to replace the Continue Watching data. 
- In the airing tab, remove the carousel and Today's schedule (I still have to think about how to make this tab good, so you can just comment those two sections for the moment.

Edit: if you wish, you can add a "progress bar" in the episode thumnail (not the anime cover in the tab)

**Comment by aleganza** [comment]
damn you so fast!

**Comment by ch0nker** [comment]
>  Remove Watchlist and keep the Continue Watching as it was, so I prefer it to be the Current data from anilist instead of the progress tracked anime. You can absolutely keep the progress tracking but I don't want to replace the Continue Watching data.

How about mixing local progress & anilist progress together?

**Comment by aleganza** [comment]
Hmm I would only keep Current data. When a local progress for an episode updates, does it also put the anime in Current?

**Comment by ch0nker** [comment]
It only updates current data like before when you're 80% done an episode. But I could probably make it update it if it doesn't already exist.

**Comment by aleganza** [comment]
Ok so we can do this:
- Current Watching section loads the Current data from anilist only
- Local progress also puts the anime in Current (due to anilist rate limiting, you make it happen only when like quitting the anime from the back button, so it happens one time only)

**Comment by ch0nker** [comment]
How about people who aren't logged into anilist? The "Continue Watching" section wouldn't show.

Edit: I'll just make it use local progress if they're not logged in.

**Comment by ch0nker** [comment]
Added your recommendations, feel free to merge after checking it out. I don't think I'm going to be able to add the progress bars while keeping it look like your style because I'm not great at css, unless you want to do that I already have it coded in just need to do css.

**Comment by aleganza** [comment]
immagine
gonna make a dropdown, sorry 😞

**Comment by ch0nker** [comment]
> immagine gonna make a dropdown, sorry 😞

lol it’s all good definitely better that way

**Pull request merged**
