### PR TITLE
Bug fixes, Skip Improvements, Recommended Anime, and other improvements

### PR DESCRIPTION
**Pull request by ch0nker**
forgot to add add some stuff to the previous PR which is why I marked as a draft.

# Todo
- [x] Update cached episodes list if a new episode exists.
- [x] Try to figure out what's causing the video player to lag so much.
- [x] Fix skip event progress bars counting as their own progress and if you hover over the start of them it'll show 0:00 instead of where ever the skip event starts at.
- [x] Fix title spacing
- [x] Second episode progress bar for showing how much is left

# Changes
- [x] Fix setting seek time in the settings tab.
- [x] Update local history when new episode is available.
- [x] Better logic for getting related anime formats.
- [x] Show skip events on the progress bar.
- [x] Make skip button popup instead of having to interact with the video player for it to show.
- [x] Drop down for Recommended & Related anime, it'll default to Related if it's available.
- [x] Episode progress bars in the anime modal (needs some refining).
- [x] Recommended anime section that'll use a random history entry.
- [x] Batch fetch anilist watch history instead of making a bunch of requests. 
- [x] 18+ filter.
- [x] Cache anime data so getting episode info doesn't take as long.
- [x] HiAnime source

# Issues
- #159 : filters 18+ content for searching and the aired anime.
- #162: removes pausing anime.
- #151: vvvv
- #153: helps load episodes faster by caching anime info.

# Screenshots
Screenshot_20240923_031202
Screenshot_20240923_101440
Screenshot_20240923_221207
Screenshot_20240925_002619
Screenshot_20240929_091948
Screenshot_20240929_092701

### CODE REVIEW

**Comment by aleganza** [comment]
could you make some additions to the skip intro / skip outro system?
like reproducing Netflix behaviors, so the skip intro button pops out apart from the video player controls, stays there for 5 seconds and then it disappears.
then, implementing the "auto next episode" to the skip outro button. same way, when the skip outro button pops out, it stays for 5 seconds and then it automatically skips to the next episode/to the sequel.

if you don't have time/you can't do it now there are no problems of course, I asked you just because you build the whole aniskip system

edit: thanks!

**Comment by ch0nker** [comment]
> could you make some additions to the skip intro / skip outro system? like reproducing Netflix behaviors, so the skip intro button pops out apart from the video player controls, stays there for 5 seconds and then it disappears. then, implementing the "auto next episode" to the skip outro button. same way, when the skip outro button pops out, it stays for 5 seconds and then it automatically skips to the next episode/to the sequel.
> 
> if you don't have time/you can't do it now there are no problems of course, I asked you just because you build the whole aniskip system
> 
> edit: thanks!

Added it lmk if there is anything else you'd be interested in me adding or if there is anything wrong with it.

It'll only autoplay to the next episode if there is less than 15 seconds left of the video after skipping to the end of the outro.

**Comment by ch0nker** [comment]
@aleganza If you could make a dropdown for the anime section where the section title is that'd be greatly appreciated so instead of having the recommended anime and the related anime next to each other it can just be one section.

**Comment by aleganza** [comment]
sorry can you provide an example

**Comment by ch0nker** [comment]
> sorry can you provide an example

sorry I don't really have any paint tools installed rn but if you could make where the text is like 'Related' or 'Recommended' into a dropdown list so you can choose between Related or Recommended.

Edit: didn't realize how easy it was to just put a Select element where the label should be.

**Comment by aleganza** [comment]
love the flags in the source selector, you can keep them, but I don't like showing the providers but instead I prefer showing "English"/"Italian" etc.
since you already added hianime, you can keep that but display it as "English Alt"

**Comment by ch0nker** [comment]
> love the flags in the source selector, you can keep them, but I don't like showing the providers but instead I prefer showing "English"/"Italian" etc. since you already added hianime, you can keep that but display it as "English Alt"

Alright

**Comment by aleganza** [comment]
love you work and effort btw 🙏

**Comment by ch0nker** [comment]
> love you work and effort btw 🙏

Thank you. A lot of this is just me learning typescript and react so there is probably some fixes/rewrites to be had.

**Comment by aleganza** [comment]
I'm gonna review it now. you still have changes to do since it's drafted?

**Comment by ch0nker** [comment]
> you still have changes to do since it's drafted?

Yeah if you press next episode when you have selected hianime and there is some captions left it'll show on the next video still have to figure out why it's doing that

**Comment by aleganza** [comment]
immagine
please fix that spacing when the title needs only 1 row, I guess you changed it

**Comment by aleganza** [comment]
alright, I'll wait for the pr status to become green again.
meanwhile, I have some changes to ask you to do about the pr:

- [ ] the title thing I mentioned before
- [ ] in settings the default source should be English (when I opened the settings tab it was blank)
- [ ] about the episode progress bar, I would not show only the watched part (pink bar) but also the remaining with like a transparent style

edit: you added hianime, was it already available on consumet or did you code the scraper?

**Comment by ch0nker** [comment]
> edit: you added hianime, was it already available on consumet or did you code the scraper?

Made it myself by scraping some of hianime and then used aniwatch api for getting the sources.

**Comment by aleganza** [comment]
and the code for the scraping is directly in akuse?

edit: just confirmed that. I would prefer you to move it either in consumet or in a new another repo of yours.
        I wouldn't like to have the scraping code directly in the app. it's ok for you?

**Comment by ch0nker** [comment]
> and the code for the scraping is directly in akuse?
> 
> 
> 
> edit: just confirmed that. I would prefer you to move it either in consumet or in a new another repo of yours.
> 
>         I wouldn't like to have the scraping code directly in the app. it's ok for you?

Seems like consument already has hianime it's just under the zoro provider lol whoops

**Comment by aleganza** [comment]
yea don't know if it works though. anyway what matters is that no scraping code is in akuse

**Comment by ch0nker** [comment]
> about the episode progress bar, I would not show only the watched part (pink bar) but also the remaining with like a transparent style

Added the second progress bar to show how much is remaining but I didn't make it transparent since making the rounded corners fit was too much of a hassle.

**Comment by aleganza** [comment]
if I can, tomorrow I'll review it

**Comment by ch0nker** [comment]
Found some more bugs so I'm going to set it as a draft until I can fix them.

**Comment by aleganza** [comment]
ook.

please list those bugs in the pr description in another selectable list

**Comment by aleganza** [comment]
about the bug fixex:

modals must not be deleted, otherwise it would have to fetch episodes info again
I would ask you to **completely** remove all the caching stuff related to the player. there is another method to improve the episode loading in-player, which I will do myself (and maybe that's causing the lag).

btw, is the lag from the video player happening only in THIS pr, or in the current released akuse?

**Comment by ch0nker** [comment]
> I would ask you to completely remove all the caching stuff related to the player. there is another method to improve the episode loading in-player, which I will do myself (and maybe that's causing the lag).

It isn't caching anything for the player only anime info so you don't have to search for the anime every time you press next episode.

> (and maybe that's causing the lag).

Nope seems that having a delay for mouse movement caused the "lag" I was trying to fix (or I did something else that fixed it). Seems to be some other lag which is only caused when the video is playing no idea what's causing it though since it's been like that since before I've made any PRs (I tested 1.5.0 and it has it), probably hls. It isn't noticeable enough to see any differences except for when you're interacting with the UI stuff like the pause icon.

> btw, is the lag from the video player happening only in THIS pr, or in the current released akuse?

currently released

**Comment by aleganza** [comment]
can you try with 1.3.0 too?

**Comment by ch0nker** [comment]
> can you try with 1.3.0 too?

Happens with 1.3.0 as well

**Comment by aleganza** [comment]
ok I have it too sometimes with all the versions on the pc I'm actually using (thinkpad t450), I didn't have it when using akuse on my home desktop.
what are your pc specs? I think it's related to that

**Comment by aleganza** [comment]
wow thanks for hianime! it provides so many languages

**Comment by ch0nker** [comment]
> what are your pc specs? I think it's related to that

Ah forgot that I bottlenecked my cpu to 1GHz because it was overheating too much probably why lol

**Comment by aleganza** [comment]
oh it must be that then.
btw, did you completely fix #162 ?

**Comment by ch0nker** [comment]
> btw, did you completely fix #162 ?

Nah removed setting the anime as paused though the issue seems to be a preference for them so I didn't really put all that much effort into fixing it.

**Pull request merged**
