### PR TITLE
feat: added next episode caching

### PR DESCRIPTION
**Pull request by synthofficial**
When the current episode is loading/loaded, it will have the next episode's data cached which will allow for instant skipping, instead of the current 3-5 second wait.

I don't know React too much so someone could probably optimise this further.

### CODE REVIEW

**Comment by aleganza** [comment]
cool! why there are also activity status changes though 🤔

**Comment by synthofficial** [comment]
honestly, i couldnt tell you. i put the new feature changes in a different fork and made this pr based off of that but its still here smh

**Comment by aleganza** [comment]
to avoid conflicts of any type, I won't check/merge before its fix

**Comment by aleganza** [comment]
gonna close, I'd like to fix it myself by implementing another system

**Pull request closed without merging**
