### PR TITLE
macOS support

### PR DESCRIPTION
**Pull request by 0x96EA**
Hi again it's been a while 👋

Congrats on the 1.0 release btw 🎉

I have a macOS version working perfectly so far. Just made some slight adjustments.

- Adjusted macOS app icon since it was too big
- Moved window controls to the left hand side
- Update the imgur link in the README with a local file (was taking to ages to load on my machine while I tried to read the docs)
- Login works with deep links and will show an error if the login fails.

Would be great if you could include macOS releases as well going forward please? Not sure what is required for GitHub Actions to build them? I can build locally on my device and will use the app for a few days and see if I notice any issues.

### Updated window controls

window controls

### Login success

login success

### Login error

login error

### Improved app icon on macOS

dock

<br>

### CODE REVIEW

**Comment by aleganza** [comment]
awesome! I'll just ask you to do a little edit: instead of displaying window controls to the left, hide the bar and show the default ones (only macos).

if you need help I can do it too, this way you can test it already.

edit: instead of 28px. you can put 25 as controls height btw

**Comment by 0x96EA** [comment]
Done!

Screenshot 2024-06-10 at 14 02 54

<br>
<br>

Screenshot 2024-06-10 at 14 02 40

<br>
<br>

Screenshot 2024-06-10 at 14 02 28

<br>

**Comment by aleganza** [comment]
I guess by the code that second-instance handler doesn't work on macos deep link, but we have to call open-url instead?

edit: basing on the last screenshot, do they disappear when the video is in fullscreen?

**Comment by 0x96EA** [comment]
Yup. See https://www.electronjs.org/docs/latest/tutorial/launch-app-from-url-in-another-app#examples

Yes they disappear when you fullscreen the app 👍

**Comment by aleganza** [comment]
I'll do a couple fixes and when I'm done I'll ask you to build the version. Thanks again for the support.

Edit: you can build now! when you're ready, create a dropbox account and upload there the build files if its's ok for you.

**Comment by 0x96EA** [comment]
I have never made an official build before so just want to review the process to make sure I don't include any personal information at build time. Will you know when that is done 👍

**Comment by aleganza** [comment]
hi! any news?
I'll also need to give you the anilist stuff

**Pull request merged**
